global:
  scrape_interval: 5s
  
scrape_configs:
  - job_name: 'api01-read-prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api01:8080']
      # - targets: ['host.docker.internal:8080']
  
  - job_name: 'apiqueue01-read-prometheus'
    static_configs:
    - targets: ['apiqueue:8080']
  
  - job_name: 'rabbitmq'
    static_configs:
    - targets: ['rabbitmq:15692']