name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore ./ContatosRegionais.sln
        
      - name: Build Solution
        run: dotnet build ./ContatosRegionais.sln --configuration Release

      - name: Run Integration Tests
        run: dotnet test ./tests/ContatosRegionais.Api.Tests/ContatosRegionais.Api.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Run Unit Tests
        run: dotnet test ./tests/ContatosRegionais.Domain.Tests/ContatosRegionais.Domain.Tests.csproj --configuration Release --no-build --logger trx --verbosity normal
